#!/bin/sh

rsync -Cavuzr --files-from=/home/lonnon/.backup-files \
    --exclude-from=/home/lonnon/.backup-exclude \
    /home/lonnon /mnt/d/lonnon/OneDrive/wsl-backups/gabriel \
  && rsync -Cavuzr --files-from=/home/lonnon/.backup-files-appdata \
    /mnt/c/Users/lonnon/AppData /mnt/d/lonnon/OneDrive/wsl-backups/gabriel/appdata \
  && touch /home/lonnon/.backup-success
