#!/bin/sh

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
ctags --recurse --options="$dir/.ctags" --exclude="$dir/../.gitignore" --tag-relative -f"$dir/$$.tags" "$dir/.."
LC_ALL=C sed -i '' -E '/^(if|switch|function|module\.exports|it|describe).+language:js$/d' "$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"

