#!/bin/sh

# Don't do anything unless asked to by environment variable.
if [ -z $GIT_PREPEND_BRANCH ]; then
  exit
fi

branch=$(git rev-parse --abbrev-ref HEAD)
msg=$(cat $1)

if [ "$branch" == "HEAD" ]
then
  exit
fi

if ! [[ "$msg" =~ ^\[$branch\] ]]
then
  echo -n "[$branch] $msg" > $1
fi
